cd: add AWS account Id

diff --git a/.github/workflows/aws-cd.yml b/.github/workflows/aws-cd.yml
--- a/.github/workflows/aws-cd.yml
+++ b/.github/workflows/aws-cd.yml
@@ -17,11 +17,28 @@ jobs:
       contents: read
     steps:
       - uses: actions/checkout@v2
+      - name: Determine AWS Account ID
+        run: |
+             if [[ "${{ github.ref_name }}" == "dev" ]]; then
+               echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_DEV }}" >> $GITHUB_ENV
+             elif [[ "${{ github.ref_name }}" == "homolog" ]]; then
+               echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_HOMOLOG }}" >> $GITHUB_ENV
+             elif [[ "${{ github.ref_name }}" == "prod" ]]; then
+               echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_PROD }}" >> $GITHUB_ENV
+             else
+               echo "Invalid branch name!" && exit 1
+             fi
+      - name: Use Node.js 18.x
+        uses: actions/setup-node@v3
+        with:
+          node-version: 18.x
+      - uses: actions/checkout@v2
       - name: Setup AWS Credentials
+        id: aws-credentials
         uses: aws-actions/configure-aws-credentials@v2
         with:
           aws-region: ${{ vars.AWS_REGION }}
-          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActionsRole
+          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/GithubActionsRole
           role-session-name: github-action
       - name: Use Node.js 18.x
         uses: actions/setup-node@v3
@@ -43,11 +60,10 @@ jobs:
       - name: Setup envs
         run: |
           echo AWS_REGION=${{ vars.AWS_REGION }} >> $GITHUB_ENV
-          echo AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }} >> $GITHUB_ENV
+          echo AWS_ACCOUNT_ID=${{ env.AWS_ACCOUNT_ID }} >> $GITHUB_ENV
           echo STACK_NAME=${{ env.STACK_NAME }} >> $GITHUB_ENV
           echo GITHUB_REF_NAME=${{ github.ref_name }} >> $GITHUB_ENV
           echo ACM_CERTIFICATE_ARN=${{ secrets.DEVMAUA_ACM_CERTIFICATE_ARN }} >> $GITHUB_ENV
-          echo HOSTED_ZONE_ID=${{ secrets.DEVMAUA_HOSTED_ZONE_ID }} >> $GITHUB_ENV
           echo ALTERNATIVE_DOMAIN_NAME=${{ vars.ALTERNATIVE_DOMAIN_NAME }} >> $GITHUB_ENV
           echo AWS_BUCKET_ASSETS=${{ vars.AWS_BUCKET_ASSETS }} >> $GITHUB_ENV
           echo VITE_RESERVATION_API=${{ vars.VITE_RESERVATION_API }} >> $GITHUB_ENV
